'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import {
  Sprout,
  ShieldCheck,
  TrendingUp,
  Truck,
  Sparkles,
  Award,
  Users,
  Building2,
  FileText,
  Code2,
  Database,
  Layers,
  Smartphone,
  ExternalLink,
  ChevronRight,
  ArrowRight,
  Heart,
  BookOpen,
  Cpu,
  Lock,
  Boxes,
  CheckCircle2,
  Globe,
  Calculator,
  Scan,
  Mic,
  QrCode,
  Share2,
  CloudSun,
  KeyRound,
  HardDrive,
  Camera,
  HelpCircle,
  Clock,
  DollarSign,
  Palette,
} from 'lucide-react';

export default function DocumentationPage() {
  const [activeTab, setActiveTab] = useState<'overview' | 'architecture' | 'features' | 'pitch' | 'team'>('overview');

  return (
    <div className="min-h-screen bg-[#f8faf6] text-slate-900 pb-20">
      {/* Documentation Header Banner */}
      <section className="relative bg-gradient-to-r from-slate-950 via-emerald-950 to-slate-950 text-white py-16 sm:py-24 border-b border-emerald-900/40 overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center opacity-20 pointer-events-none"
          style={{ backgroundImage: `url('https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1920&q=80')` }}
        />
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-emerald-500/15 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-xs font-black uppercase tracking-wider text-emerald-300 bg-emerald-950/80 border border-emerald-400/30 px-3 py-1 rounded-full flex items-center gap-1.5">
              <Building2 className="w-3.5 h-3.5 text-amber-400" />
              <span>Company: AnoS</span>
            </span>
            <span className="text-xs font-bold text-amber-300 bg-amber-950/80 border border-amber-500/30 px-3 py-1 rounded-full flex items-center gap-1.5">
              <Heart className="w-3.5 h-3.5 text-rose-400 fill-rose-400" />
              <span>Made by Kuber Narute &amp; Team</span>
            </span>
            <span className="text-xs font-bold text-teal-300 bg-teal-950/80 border border-teal-500/30 px-3 py-1 rounded-full flex items-center gap-1.5">
              <Palette className="w-3.5 h-3.5 text-pink-400" />
              <span>Frontend Generated by Google Stitch</span>
            </span>
            <span className="text-xs font-bold text-blue-300 bg-blue-950/80 border border-blue-500/30 px-3 py-1 rounded-full">
              PWA 2.0 &bull; Next.js 14 &bull; Hybrid DB
            </span>
          </div>

          <h1 className="text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight text-white">
            KisanDirect Technical Dossier &amp; Judge Presentation
          </h1>

          <p className="text-base sm:text-lg text-emerald-100 max-w-3xl leading-relaxed font-normal">
            The complete architectural specification, APIs, database models, image pipeline, and presentation cheat sheet for Maharashtra's premier AI-powered direct farmgate agricultural marketplace.
          </p>

          {/* Quick Nav Tabs */}
          <div className="flex flex-wrap gap-2 pt-4">
            {[
              { id: 'overview', label: '1. Executive Overview', icon: BookOpen },
              { id: 'architecture', label: '2. System Architecture & Tech Stack', icon: Layers },
              { id: 'features', label: '3. Detailed Feature Breakdown', icon: Cpu },
              { id: 'pitch', label: '4. Judge Pitch & Demo Flow', icon: Award },
              { id: 'team', label: '5. Company & Team Credits', icon: Users },
            ].map((t) => {
              const Icon = t.icon;
              return (
                <button
                  key={t.id}
                  onClick={() => setActiveTab(t.id as any)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-bold transition ${
                    activeTab === t.id
                      ? 'bg-emerald-500 text-slate-950 shadow-lg shadow-emerald-500/25 scale-105'
                      : 'bg-slate-900/80 text-slate-300 hover:bg-slate-800 border border-slate-700'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  <span>{t.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </section>

      {/* Main Content Area */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* ======================================================== */}
        {/* TAB 1: EXECUTIVE OVERVIEW                                */}
        {/* ======================================================== */}
        {activeTab === 'overview' && (
          <div className="space-y-10">
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
                  <Sprout className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-black text-slate-900">Executive Summary &amp; Problem Statement</h2>
                  <p className="text-xs text-slate-500">Built by Kuber Narute and his team at AnoS &bull; UI Generated with Google Stitch</p>
                </div>
              </div>

              <div className="prose prose-slate max-w-none text-xs sm:text-sm text-slate-700 leading-relaxed space-y-4">
                <p>
                  <strong>The Crisis in Indian Agriculture:</strong> In Maharashtra and across India, farmers currently surrender <strong>45% to 55% of the end-consumer price</strong> to a multi-tiered cartel of intermediaries: village aggregators (katcha arhatiyas), APMC commission agents (pucca arhatiyas), secondary wholesalers, transport cartels, and urban retail middlemen.
                </p>
                <p>
                  In addition to massive price cuts, farmers suffer <strong>18% to 25% post-harvest spoilage</strong> due to fragmented cold storage, arbitrary auction rejections, delayed credit cycles of 30–60 days, and complete price opacity.
                </p>
                <p>
                  <strong>The KisanDirect Solution:</strong> Engineered by <strong>Kuber Narute and team at AnoS</strong>, KisanDirect is a unified farm-to-buyer disintermediation platform. It replaces 5 middlemen tiers with a single <strong>2% direct platform fee</strong>, guarantees real-time APMC price benchmarks, provides computer-vision crop pathology diagnosis, offers an interactive Profit Calculator, enables 2-hour digital escrow release via UPI QR codes, and delivers automated 1-click WhatsApp connectivity.
                </p>
              </div>

              {/* Impact Metrics Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 pt-4">
                <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5 text-center">
                  <span className="text-3xl font-black text-emerald-700 block">+35% to +45%</span>
                  <span className="text-xs font-bold text-slate-700 block mt-1">Farmer Price Realization</span>
                  <p className="text-[11px] text-slate-500 mt-1">Direct payout without auction agent deductions.</p>
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-2xl p-5 text-center">
                  <span className="text-3xl font-black text-blue-700 block">-20% to -28%</span>
                  <span className="text-xs font-bold text-slate-700 block mt-1">Buyer Sourcing Cost</span>
                  <p className="text-[11px] text-slate-500 mt-1">Wholesale procurement at farmgate rates.</p>
                </div>

                <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 text-center">
                  <span className="text-3xl font-black text-amber-700 block">2 Hours</span>
                  <span className="text-xs font-bold text-slate-700 block mt-1">Escrow Settlement</span>
                  <p className="text-[11px] text-slate-500 mt-1">Direct bank transfer via UPI upon inspection.</p>
                </div>

                <div className="bg-purple-50 border border-purple-200 rounded-2xl p-5 text-center">
                  <span className="text-3xl font-black text-purple-700 block">0 Middlemen</span>
                  <span className="text-xs font-bold text-slate-700 block mt-1">Transparent Value Chain</span>
                  <p className="text-[11px] text-slate-500 mt-1">Transparent 2% platform fee replacing 55% cuts.</p>
                </div>
              </div>
            </div>

            {/* Target Value Chain */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <h3 className="text-xl font-black text-slate-900">Supported Personas &amp; Stakeholders</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs sm:text-sm">
                <div className="border border-slate-200 rounded-2xl p-5 space-y-2.5">
                  <h4 className="font-bold text-emerald-800 text-base flex items-center gap-2">
                    <Sprout className="w-5 h-5 text-emerald-600" />
                    <span>1. Producers, Farmers &amp; FPOs</span>
                  </h4>
                  <p className="text-slate-600">
                    Full autonomy to list produce with harvest dates, variety, and photos. Access AI price guidance based on live APMC mandis. Receive counter-offers and guaranteed payments without debtor risk.
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2.5">
                  <h4 className="font-bold text-blue-800 text-base flex items-center gap-2">
                    <Users className="w-5 h-5 text-blue-600" />
                    <span>2. Households &amp; Consumers</span>
                  </h4>
                  <p className="text-slate-600">
                    Farm-to-fork freshness delivered within 24-36 hours. Complete traceability with farmer profile photos, land coordinates, and organic certification badges.
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2.5">
                  <h4 className="font-bold text-amber-800 text-base flex items-center gap-2">
                    <TrendingUp className="w-5 h-5 text-amber-600" />
                    <span>3. Commercial Restaurants &amp; Hotels</span>
                  </h4>
                  <p className="text-slate-600">
                    Wholesale procurement with standardized Grade-A sizes, predictable morning dispatch, and consolidated GST tax invoicing.
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2.5">
                  <h4 className="font-bold text-purple-800 text-base flex items-center gap-2">
                    <Building2 className="w-5 h-5 text-purple-600" />
                    <span>4. Retail Marts &amp; Agro-Processors</span>
                  </h4>
                  <p className="text-slate-600">
                    Multi-ton bulk purchasing from temperature-controlled consolidation hubs in Pune, Nashik, Satara, and Kolhapur.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ======================================================== */}
        {/* TAB 2: SYSTEM ARCHITECTURE & TECH STACK                  */}
        {/* ======================================================== */}
        {activeTab === 'architecture' && (
          <div className="space-y-10">
            {/* Google Stitch UI Callout */}
            <div className="bg-gradient-to-r from-pink-900/90 via-purple-950 to-slate-950 text-white rounded-3xl p-8 border border-pink-500/30 shadow-xl space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-pink-500/20 border border-pink-400/40 flex items-center justify-center text-pink-300">
                  <Palette className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-[11px] font-black uppercase tracking-widest text-pink-300 bg-pink-950/80 border border-pink-500/30 px-3 py-0.5 rounded-full">
                    UI Design System Specification
                  </span>
                  <h3 className="text-2xl font-black text-white mt-1">
                    Frontend Generated &amp; Designed by Google Stitch
                  </h3>
                </div>
              </div>
              <p className="text-xs sm:text-sm text-pink-100/90 leading-relaxed">
                The entire user interface, visual layout hierarchy, color palette token system, responsive component models, mobile navigation drawer, modal dialogs, and glassmorphism styling were <strong>generated and designed using Google Stitch UI &amp; Stitch MCP</strong>. This ensured an ultra-premium, clean, accessible aesthetic optimized for rural vernacular farmers on mobile screens as well as institutional enterprise buyers on wide desktop displays.
              </p>
            </div>

            {/* Complete Tech Stack Grid */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-teal-100 text-teal-700 flex items-center justify-center font-bold">
                  <Code2 className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-black text-slate-900">End-to-End Technology Stack</h2>
                  <p className="text-xs text-slate-500">Modern, scalable, production-grade enterprise stack</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 text-xs">
                {/* Frontend */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <Layers className="w-4 h-4 text-emerald-600" />
                    <span>Frontend (Generated by Stitch)</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; <strong>Next.js 14.2.15</strong> (App Router, Server Components)</li>
                    <li>&bull; <strong>React 18.3.1</strong> with Client Hydration</li>
                    <li>&bull; <strong>TypeScript 5.6</strong> with strict typing</li>
                    <li>&bull; <strong>Tailwind CSS 3.4</strong> + Glassmorphism Tokens</li>
                    <li>&bull; <strong>Lucide React</strong> for unified SVG iconography</li>
                  </ul>
                </div>

                {/* Backend */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <Cpu className="w-4 h-4 text-blue-600" />
                    <span>Backend &amp; Serverless APIs</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; Next.js 14 Route Handlers (Edge &amp; Node.js runtime)</li>
                    <li>&bull; RESTful API endpoints for Products, Orders, AI, Weather</li>
                    <li>&bull; Role-based middleware &amp; session token verification</li>
                    <li>&bull; Automated fallback catalog for zero-downtime resilience</li>
                  </ul>
                </div>

                {/* Database */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <Database className="w-4 h-4 text-purple-600" />
                    <span>Hybrid Dual-Storage Database</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; <strong>Prisma ORM 5.22</strong> for relational modeling</li>
                    <li>&bull; <strong>SQLite</strong> for high-speed local edge queries &amp; ACID joins</li>
                    <li>&bull; <strong>Google Firebase Firestore 12.18</strong> for cloud sync across distributed Vercel serverless containers</li>
                    <li>&bull; Eliminates ephemeral filesystem data wipeouts</li>
                  </ul>
                </div>

                {/* APIs & Keys */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <KeyRound className="w-4 h-4 text-amber-600" />
                    <span>APIs &amp; Key Specifications</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; <strong>Google Gemini API:</strong> Generative AI agronomy &amp; pathology via <code className="bg-slate-200 px-1 rounded">GEMINI_API_KEY</code></li>
                    <li>&bull; <strong>Open-Meteo API:</strong> 100% public, <strong>0 API keys required</strong></li>
                    <li>&bull; <strong>Agmarknet / Data.gov.in:</strong> Open public data API</li>
                    <li>&bull; <strong>Web Speech API:</strong> Native client browser, <strong>0 keys required</strong></li>
                  </ul>
                </div>

                {/* Media & Images */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <Camera className="w-4 h-4 text-rose-600" />
                    <span>Image Storage &amp; Processing</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; <strong>Produce Visuals:</strong> High-res Unsplash CDN with WebP query optimization (<code className="bg-slate-200 px-1 rounded">w=800&amp;q=80</code>)</li>
                    <li>&bull; <strong>Camera Uploads:</strong> HTML5 Camera API Base64 Data URLs (<code className="bg-slate-200 px-1 rounded">data:image/jpeg;base64</code>)</li>
                    <li>&bull; <strong>PWA Assets:</strong> Local <code className="bg-slate-200 px-1 rounded">/public/icons/</code> asset pipeline</li>
                  </ul>
                </div>

                {/* Authentication & Security */}
                <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 space-y-3">
                  <div className="flex items-center gap-2 font-black text-slate-900 text-sm">
                    <Lock className="w-4 h-4 text-teal-600" />
                    <span>Auth &amp; Escrow Security</span>
                  </div>
                  <ul className="space-y-2 text-slate-600">
                    <li>&bull; Multi-persona cookie sessions (<code className="bg-slate-200 px-1 rounded">kisandirect_role</code>)</li>
                    <li>&bull; Instant 1-click persona switcher for judges</li>
                    <li>&bull; Dynamic UPI Escrow QR standard (<code className="bg-slate-200 px-1 rounded">upi://pay</code>)</li>
                    <li>&bull; Bank of Maharashtra direct deposit simulation</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Database Deep Dive Diagram */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-blue-100 text-blue-700 flex items-center justify-center font-bold">
                  <HardDrive className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-xl font-black text-slate-900">Why the Hybrid Dual-Storage Architecture?</h3>
                  <p className="text-xs text-slate-500">How KisanDirect achieves speed AND persistent global cloud synchronization</p>
                </div>
              </div>

              <div className="prose prose-slate max-w-none text-xs sm:text-sm text-slate-700 leading-relaxed space-y-3">
                <p>
                  Most hackathon projects fail when deployed to serverless environments (like Vercel or AWS Lambda) because SQLite databases in the container filesystem are <strong>ephemeral and reset on every cold boot</strong>. Listings created by a farmer on their mobile phone would disappear for a buyer on a laptop.
                </p>
                <p>
                  <strong>Our Innovative Solution:</strong> KisanDirect implements an automated dual-write and hybrid query pattern:
                </p>
              </div>

              <div className="bg-slate-950 text-slate-200 rounded-2xl p-6 font-mono text-xs overflow-x-auto space-y-2">
                <div className="text-emerald-400 font-bold">1. Farmer Action (POST /api/products):</div>
                <div className="pl-4">&bull; Writes to local Prisma SQLite for fast relational integrity and constraints.</div>
                <div className="pl-4">&bull; Simultaneously invokes <code className="text-amber-300">saveProductToFirestore()</code> in Google Firebase Firestore.</div>
                <div className="text-blue-400 font-bold mt-2">2. Buyer Query (GET /api/products):</div>
                <div className="pl-4">&bull; Concurrently queries local Prisma AND remote Google Firestore.</div>
                <div className="pl-4">&bull; Deduplicates products by unique ID and returns an unified catalog.</div>
                <div className="text-purple-400 font-bold mt-2">3. The Result:</div>
                <div className="pl-4">&bull; Products created on ANY phone or laptop remain permanently accessible across all global nodes with zero data loss!</div>
              </div>
            </div>
          </div>
        )}

        {/* ======================================================== */}
        {/* TAB 3: DETAILED FEATURE BREAKDOWN                        */}
        {/* ======================================================== */}
        {activeTab === 'features' && (
          <div className="space-y-10">
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-amber-100 text-amber-800 flex items-center justify-center font-bold">
                  <Boxes className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-black text-slate-900">Exhaustive Feature-by-Feature Breakdown</h2>
                  <p className="text-xs text-slate-500">Every single module and function explained with technical mechanics</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs sm:text-sm">
                {/* 1. Profit Calculator */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-emerald-700 bg-emerald-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Calculator className="w-3.5 h-3.5" />
                      <span>Dedicated Tool</span>
                    </span>
                    <Link href="/profit-calculator" className="text-xs font-bold text-emerald-600 hover:underline flex items-center gap-1">
                      <span>Launch Tool</span>
                      <ChevronRight className="w-3 h-3" />
                    </Link>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">1. Real-Time Farmer Profit Calculator</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Interactive ROI calculation engine that compares the Traditional APMC Mandi route versus KisanDirect. It models all hidden intermediary deductions: <strong>8% commission fee, ₹2.5/kg handling &amp; unloading, ₹3.5/kg transport, 3% moisture deduction, and 5% delayed auction spoilage</strong>. Computes real-time Net Take-Home Pay, Percentage Profit Jump (+35% to +50%), and Annual Farmer Family Savings.
                  </p>
                </div>

                {/* 2. Crop Lens */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-purple-700 bg-purple-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Scan className="w-3.5 h-3.5" />
                      <span>Computer Vision AI</span>
                    </span>
                    <Link href="/crop-lens" className="text-xs font-bold text-purple-600 hover:underline flex items-center gap-1">
                      <span>Launch Scanner</span>
                      <ChevronRight className="w-3 h-3" />
                    </Link>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">2. AI Crop Lens &amp; Disease Scanner</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Powered by Google Gemini multimodal AI and indexed crop pathology presets. Farmers upload or photograph afflicted leaves (tomatoes, onions, grapes, soybeans, cotton). The system classifies the pathogen (e.g. Early Blight, Purple Blotch, Downy Mildew), estimates severity score (%), and provides a 2-tier remedy: <strong>Organic Bio-Remedy (Neem oil, Trichoderma) and Chemical Dosage (Mancozeb, Chlorothalonil) with precise spray schedules</strong>.
                  </p>
                </div>

                {/* 3. KrushiMitra Voice AI */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-blue-700 bg-blue-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Mic className="w-3.5 h-3.5" />
                      <span>Vernacular Voice</span>
                    </span>
                    <Link href="/krushimitra" className="text-xs font-bold text-blue-600 hover:underline flex items-center gap-1">
                      <span>Talk to AI</span>
                      <ChevronRight className="w-3 h-3" />
                    </Link>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">3. KrushiMitra Conversational Voice AI</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Accessible speech-to-text and text-to-speech assistant designed for farmers with limited literacy. Uses Web Speech API (<code className="bg-slate-200 px-1 rounded">webkitSpeechRecognition</code> &amp; <code className="bg-slate-200 px-1 rounded">speechSynthesis</code>) connected to Google Gemini. Farmers can speak in Marathi, Hindi, or English to ask mandi rates, fertilizer advice, or pest solutions, and receive vocal audio responses.
                  </p>
                </div>

                {/* 4. UPI Escrow */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-rose-700 bg-rose-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <QrCode className="w-3.5 h-3.5" />
                      <span>Fintech Escrow</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">2-Hour Settlement</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">4. Universal Dynamic UPI Escrow QR</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Generates dynamic, compliant UPI QR codes (<code className="bg-slate-200 px-1 rounded">upi://pay?pa=...&amp;pn=...&amp;am=...</code>) on the fly for any lot order. Compatible with Google Pay, PhonePe, Paytm, and BHIM. When the buyer scans and pays, funds are locked in escrow. Once produce arrives at the warehouse and passes inspection, the farmer receives an instant bank credit.
                  </p>
                </div>

                {/* 5. 1-Click WhatsApp */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-green-700 bg-green-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Share2 className="w-3.5 h-3.5" />
                      <span>Social Commerce</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">Instant Viral Sharing</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">5. 1-Click WhatsApp Direct Share</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Direct integration with WhatsApp Web &amp; Mobile (<code className="bg-slate-200 px-1 rounded">wa.me/?text=...</code>). Pre-formats product lots with harvest date, price per kg, certified lot badge, and deep link. Allows farmers to broadcast their harvest to local WhatsApp buyer groups and institutional purchasers with 1 tap.
                  </p>
                </div>

                {/* 6. Live Weather */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-amber-700 bg-amber-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <CloudSun className="w-3.5 h-3.5" />
                      <span>Meteorological AI</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">Open-Meteo 0-Key</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">6. Live Weather &amp; Microclimate Alerts</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Live meteorological tracking across Maharashtra agro-climatic zones (Nashik, Pune, Solapur, Vidarbha). Retrieves temperature, relative humidity, wind velocity, and 7-day precipitation forecasts via public Open-Meteo APIs without requiring API keys. Generates proactive spraying and harvest safety advisories.
                  </p>
                </div>

                {/* 7. Agmarknet Ticker */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-teal-700 bg-teal-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <TrendingUp className="w-3.5 h-3.5" />
                      <span>Government Benchmarks</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">APMC Mandis</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">7. APMC Mandi Price Intelligence Ticker</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Streams live modal, minimum, and maximum prices from government APMC mandis (Lasalgaon, Vashi, Gultekdi Pune, Satara) for over 20 commodities. Empowers farmers with authentic pricing data so buyers cannot negotiate below fair market baseline.
                  </p>
                </div>

                {/* 8. Multilingual i18n */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-indigo-700 bg-indigo-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Globe className="w-3.5 h-3.5" />
                      <span>Vernacular Access</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">EN &bull; HI &bull; MR</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">8. Multilingual Localization (English, Hindi, Marathi)</h3>
                  <p className="text-slate-600 leading-relaxed">
                    A first-class internationalization engine with instantaneous client-side toggling between Marathi (मराठी), Hindi (हिंदी), and English. Translates navigation, buttons, crop names, profit tables, and status messages to ensure rural adoption.
                  </p>
                </div>

                {/* 9. OpenStreetMap Cold-Chain Logistics */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-blue-700 bg-blue-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Truck className="w-3.5 h-3.5" />
                      <span>Zero-Fee Telemetry</span>
                    </span>
                    <Link href="/logistics" className="text-xs font-bold text-blue-600 hover:underline flex items-center gap-1">
                      <span>View Map</span>
                      <ChevronRight className="w-3 h-3" />
                    </Link>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">9. Cold-Chain Logistics &amp; Leaflet Tracking</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Live transit telemetry built on OpenStreetMap and Leaflet 1.9 (100% free open-source mapping without expensive Google Maps billing). Visualizes 4 consolidation hubs (Pune, Nashik, Satara, Kolhapur) and 6-stage transit status with vehicle temperature telemetry.
                  </p>
                </div>

                {/* 10. Progressive Web App 2.0 */}
                <div className="border border-slate-200 rounded-2xl p-6 space-y-3 hover:border-emerald-400 transition bg-slate-50/50">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black text-amber-700 bg-amber-100 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                      <Smartphone className="w-3.5 h-3.5" />
                      <span>Installable App</span>
                    </span>
                    <span className="text-xs text-slate-500 font-semibold">Offline Ready</span>
                  </div>
                  <h3 className="font-bold text-slate-900 text-base">10. Progressive Web App (PWA 2.0)</h3>
                  <p className="text-slate-600 leading-relaxed">
                    Native app experience installed directly on Android, iPhone, and Windows via Service Worker (<code className="bg-slate-200 px-1 rounded">sw.js</code>) and Web App Manifest. Features offline shell caching for areas with unstable cellular connectivity.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ======================================================== */}
        {/* TAB 4: JUDGE PITCH & LIVE DEMO FLOW                     */}
        {/* ======================================================== */}
        {activeTab === 'pitch' && (
          <div className="space-y-10">
            {/* 2-Minute Elevator Pitch */}
            <div className="bg-gradient-to-br from-slate-950 via-emerald-950 to-slate-950 text-white rounded-3xl p-8 sm:p-12 shadow-xl border border-emerald-500/30 space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-amber-400 text-slate-950 flex items-center justify-center font-black">
                  <Clock className="w-6 h-6" />
                </div>
                <div>
                  <span className="text-xs font-bold uppercase tracking-widest text-amber-400 bg-amber-950/80 border border-amber-500/30 px-3 py-1 rounded-full">
                    Judges Presentation Script
                  </span>
                  <h2 className="text-2xl sm:text-4xl font-black text-white mt-1">
                    2-Minute Elevator Pitch For Judges
                  </h2>
                </div>
              </div>

              <div className="space-y-4 text-xs sm:text-sm text-emerald-100/90 leading-relaxed font-normal bg-emerald-950/40 p-6 rounded-2xl border border-emerald-500/20">
                <p>
                  <em>&ldquo;Respected judges, when you buy a kilo of tomatoes for ₹40 in Mumbai or Pune, do you know how much the farmer in Nashik actually received? Just ₹12 to ₹15. Over 55% of your money was swallowed by 5 tiers of commission agents, auction cartels, and speculative middlemen.&rdquo;</em>
                </p>
                <p>
                  <em>&ldquo;We are team AnoS, led by Kuber Narute. We built <strong>KisanDirect</strong>—an AI-powered, farmgate-to-buyer disintermediation platform. With KisanDirect, the farmer gets ₹28 per kilo, the buyer pays ₹32, and our platform charges a transparent 2% escrow fee. Everybody wins except the exploitative middleman.&rdquo;</em>
                </p>
                <p>
                  <em>&ldquo;Our entire frontend was <strong>generated and designed using Google Stitch</strong> for an ultra-responsive, vernacular-first mobile experience. We solved the serverless database challenge with a hybrid architecture combining local Prisma SQLite with real-time Google Firebase Firestore cloud sync. We’ve built in an AI Crop Disease Lens, a real-time Profit Calculator, KrushiMitra Voice AI, and universal UPI Escrow QR codes.&rdquo;</em>
                </p>
              </div>
            </div>

            {/* Recommended 3-Step Live Demo Flow */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <h3 className="text-xl font-black text-slate-900 flex items-center gap-2">
                <Award className="w-5 h-5 text-amber-500" />
                <span>Recommended 3-Step Hackathon Live Demo Flow</span>
              </h3>

              <div className="space-y-4 text-xs sm:text-sm">
                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <div className="flex items-center gap-2 font-black text-emerald-700">
                    <span className="w-6 h-6 rounded-full bg-emerald-100 flex items-center justify-center text-xs">1</span>
                    <span>Step 1: The Economic Proof &mdash; Profit Calculator</span>
                  </div>
                  <p className="text-slate-600">
                    Navigate to <Link href="/profit-calculator" className="font-bold text-emerald-600 underline">/profit-calculator</Link>. Slide the quantity to 2,000 kg and show the judges the side-by-side comparison: how traditional mandi deductions siphon away ₹28,000 in hidden fees versus KisanDirect keeping 98% of the value in the farmer's pocket.
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <div className="flex items-center gap-2 font-black text-purple-700">
                    <span className="w-6 h-6 rounded-full bg-purple-100 flex items-center justify-center text-xs">2</span>
                    <span>Step 2: The Deep Tech AI &mdash; Crop Lens Scanner</span>
                  </div>
                  <p className="text-slate-600">
                    Navigate to <Link href="/crop-lens" className="font-bold text-purple-600 underline">/crop-lens</Link>. Click on a preset leaf sample (e.g. Tomato Early Blight or Onion Purple Blotch) or take a live photo. Watch the AI instantly output pathogen diagnosis, severity percentage, and organic Neem/Trichoderma recipes.
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <div className="flex items-center gap-2 font-black text-blue-700">
                    <span className="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center text-xs">3</span>
                    <span>Step 3: Direct Trade &amp; UPI Escrow Checkout</span>
                  </div>
                  <p className="text-slate-600">
                    Go to <Link href="/marketplace" className="font-bold text-blue-600 underline">/marketplace</Link>, click on any certified produce lot, and click <strong>&ldquo;Pay via UPI Escrow&rdquo;</strong>. Show the dynamically generated UPI QR code that the buyer scans with any mobile banking app, and explain the automated 2-hour settlement release.
                  </p>
                </div>
              </div>
            </div>

            {/* Anticipated Judge Questions & Answers */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-6">
              <h3 className="text-xl font-black text-slate-900 flex items-center gap-2">
                <HelpCircle className="w-5 h-5 text-blue-500" />
                <span>Anticipated Judge Questions &amp; Bulletproof Answers</span>
              </h3>

              <div className="space-y-4 text-xs sm:text-sm">
                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <h4 className="font-bold text-slate-900 text-sm">
                    Q: &ldquo;How did you design and build this complex frontend so quickly?&rdquo;
                  </h4>
                  <p className="text-slate-600">
                    <strong>Answer:</strong> &ldquo;We leveraged <strong>Google Stitch UI &amp; Stitch MCP</strong> to generate our accessible component architecture, glassmorphism styling, responsive cards, and mobile navigation tokens. This allowed our team to focus heavily on core business logic, hybrid cloud synchronization, and AI integration.&rdquo;
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <h4 className="font-bold text-slate-900 text-sm">
                    Q: &ldquo;Why not use a standard SQL database on AWS or Supabase? Why hybrid SQLite + Firebase?&rdquo;
                  </h4>
                  <p className="text-slate-600">
                    <strong>Answer:</strong> &ldquo;We wanted the best of both worlds: extreme local development speed and zero-friction relational modeling via Prisma and SQLite, combined with Google Firebase Firestore for global cloud multi-container sync. This ensures that even when deployed on serverless hosting where local files are ephemeral, all farmer listings are instantly persisted and synchronized in real time across the globe.&rdquo;
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <h4 className="font-bold text-slate-900 text-sm">
                    Q: &ldquo;How do you handle Indian farmers who cannot read or write English?&rdquo;
                  </h4>
                  <p className="text-slate-600">
                    <strong>Answer:</strong> &ldquo;We implemented 3 specific features for rural accessibility: first, full vernacular multilingual toggling between Marathi, Hindi, and English; second, KrushiMitra Voice AI allowing farmers to speak in their mother tongue; and third, 1-click WhatsApp integration which they already use daily.&rdquo;
                  </p>
                </div>

                <div className="border border-slate-200 rounded-2xl p-5 space-y-2">
                  <h4 className="font-bold text-slate-900 text-sm">
                    Q: &ldquo;What are your infrastructure and API costs?&rdquo;
                  </h4>
                  <p className="text-slate-600">
                    <strong>Answer:</strong> &ldquo;Near zero! Open-Meteo weather API is 100% public with no keys. Web Speech API is client-native in the browser. OpenStreetMap Leaflet tiles are free. UPI QR generation is protocol-native. Only Gemini AI uses an API key, which has generous free tier limits for agro-pathology.&rdquo;
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ======================================================== */}
        {/* TAB 5: COMPANY PROFILE & TEAM CREDITS                    */}
        {/* ======================================================== */}
        {activeTab === 'team' && (
          <div className="space-y-10">
            {/* Company Banner */}
            <div className="bg-gradient-to-br from-slate-900 via-emerald-950 to-slate-950 text-white rounded-3xl p-8 sm:p-12 shadow-xl border border-emerald-500/30 space-y-6">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div>
                  <span className="text-xs font-black uppercase tracking-widest text-amber-400 bg-amber-950/80 border border-amber-500/30 px-3 py-1 rounded-full">
                    Parent Organization
                  </span>
                  <h2 className="text-3xl sm:text-5xl font-black text-white mt-2">
                    Company: AnoS
                  </h2>
                </div>
                <div className="glass-emerald px-4 py-2 rounded-2xl text-xs font-bold text-emerald-200 border border-emerald-400/40">
                  Agri-Tech &bull; Innovation Labs
                </div>
              </div>

              <p className="text-sm sm:text-base text-emerald-100/90 max-w-2xl leading-relaxed">
                <strong>AnoS</strong> is a forward-thinking technology enterprise dedicated to building transformative digital products that democratize access, eliminate friction, and unlock radical economic efficiency in core Indian sectors.
              </p>
            </div>

            {/* Creators & Leadership Credit Card */}
            <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200 shadow-sm space-y-8">
              <div className="border-b border-slate-200 pb-6">
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
                  Engineering &amp; Product Leadership
                </span>
                <h3 className="text-2xl font-black text-slate-900 mt-2">
                  Project Lead: Kuber Narute &amp; Team
                </h3>
                <p className="text-xs sm:text-sm text-slate-500 mt-1">
                  The visionary architects and engineers behind the conception, design, and execution of KisanDirect.
                </p>
              </div>

              {/* Team Members Card */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-slate-50 border border-emerald-200/80 rounded-2xl p-6 space-y-4">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-emerald-600 to-teal-500 text-white font-black text-2xl flex items-center justify-center shadow-lg shadow-emerald-600/30">
                    KN
                  </div>
                  <div>
                    <h4 className="text-lg font-black text-slate-900">Kuber Narute</h4>
                    <span className="text-xs font-bold text-emerald-700 block">Lead Architect, Product Visionary &amp; Engineering Lead</span>
                    <span className="text-[11px] text-slate-500 font-medium block mt-0.5">Company: AnoS</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Spearheaded the platform architecture, multi-container cloud synchronization strategy, algorithmic APMC pricing integration, and progressive web application implementation.
                  </p>
                </div>

                <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 space-y-4">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-500 text-white font-black text-2xl flex items-center justify-center shadow-lg shadow-blue-600/30">
                    AT
                  </div>
                  <div>
                    <h4 className="text-lg font-black text-slate-900">AnoS Team Mates &amp; Collaborators</h4>
                    <span className="text-xs font-bold text-blue-700 block">Core Development, Logistics &amp; Product Design</span>
                    <span className="text-[11px] text-slate-500 font-medium block mt-0.5">Company: AnoS</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Contributed across user interface design generated with Google Stitch, Leaflet OpenStreetMap telemetry integration, agricultural domain modeling for Maharashtra APMC clusters, and quality assurance.
                  </p>
                </div>
              </div>

              {/* Dedication Statement */}
              <div className="bg-emerald-900 text-white rounded-2xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="space-y-1 text-center sm:text-left">
                  <h4 className="font-bold text-sm text-emerald-200 flex items-center gap-1.5 justify-center sm:justify-start">
                    <Heart className="w-4 h-4 text-rose-400 fill-rose-400" />
                    <span>Built For India's Annadata (Farmers)</span>
                  </h4>
                  <p className="text-xs text-emerald-100">
                    Proudly designed with Google Stitch and developed with precision by Kuber Narute and team at AnoS.
                  </p>
                </div>

                <Link
                  href="/marketplace"
                  className="bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black px-6 py-3 rounded-xl text-xs transition shrink-0"
                >
                  Explore The Platform
                </Link>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
